// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRe7hzLuUiOacuaX14UkmWBGblqG3aDc',
    appId: '1:228772173395:web:d04798b787f6a0b92698a6',
    messagingSenderId: '228772173395',
    projectId: 'flutter-1c291',
    authDomain: 'flutter-1c291.firebaseapp.com',
    storageBucket: 'flutter-1c291.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRkNUSFZVa8sR7PfZavw39GWMsU0dh5oE',
    appId: '1:228772173395:android:9a5989a89d84fd112698a6',
    messagingSenderId: '228772173395',
    projectId: 'flutter-1c291',
    storageBucket: 'flutter-1c291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSy35oo9ZvlgARHNSqLPJGXMFJKFRy3E',
    appId: '1:228772173395:ios:3da1360d3b1a918e2698a6',
    messagingSenderId: '228772173395',
    projectId: 'flutter-1c291',
    storageBucket: 'flutter-1c291.appspot.com',
    iosClientId: '228772173395-b50gqk4c1fea29f2cuhla0qve5rgvq9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSy35oo9ZvlgARHNSqLPJGXMFJKFRy3E',
    appId: '1:228772173395:ios:126285b4097ba49f2698a6',
    messagingSenderId: '228772173395',
    projectId: 'flutter-1c291',
    storageBucket: 'flutter-1c291.appspot.com',
    iosClientId: '228772173395-25ttbhk03hl4stabs5gmgm4pun1gqn4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
